### ISSUE TITLE
Cannot use GPU in CPU-only Caffe: check mode.

### ISSUE THREAD

**Issue by EllieLily** [GehenHe/Face-Verifiction-on-Camera#1]
Hi!  I'm trying to  run this demo,but I get the error below:
I0504 15:39:17.185148  7112 net.cpp:270] This network produces output dropout1
I0504 15:39:17.185176  7112 net.cpp:283] Network initialization done.
I0504 15:39:17.235440  7112 net.cpp:761] Ignoring source layer data
I0504 15:39:17.235486  7112 net.cpp:761] Ignoring source layer label_data_1_split
I0504 15:39:17.240262  7112 net.cpp:761] Ignoring source layer fc2
I0504 15:39:17.240305  7112 net.cpp:761] Ignoring source layer fc2_fc2_0_split
I0504 15:39:17.240319  7112 net.cpp:761] Ignoring source layer accuracy
I0504 15:39:17.240329  7112 net.cpp:761] Ignoring source layer loss
/usr/local/lib/python2.7/dist-packages/skimage/transform/_warps.py:84: UserWarning: The default mode, 'constant', will be changed to 'reflect' in skimage 0.15.
  warn("The default mode, 'constant', will be changed to 'reflect' in "
F0504 15:39:17.445216  7112 conv_layer.cpp:76] Cannot use GPU in CPU-only Caffe: check mode.
*** Check failure stack trace: ***
I use cpu-only mode and I changed the mode in the Makefile.config  file,but the error still appears.
please help me.

**Comment by GehenHe** [comment]
sorry for so late reply...
I think this may due to I use `caffe.set_mode_gpu()` in `/preprocess/feature_engine.py`, you can remove this line.

**Comment by EllieLily** [comment]
@GehenHe  It works , thank you very much！
